### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by roverwolf** [RANDA-Solutions/OCP2_0.PublishingService#1]
The code for the OpenCredentialPublisher packages Clrs, Cryptography, and VerifiableCredentials appear to be missing from the OCP_2.0 repositories.

I am assuming all have changes from what is in the Open-Credential-Publisher-Publishing-Service repository, but at minimum the Clrs package from that repository does not have Clrs.v1_0 and Clrs.v2_0 that the new code is looking for.

OpenCredentialPublisher.JsonLD and JsonLd.Normalization also cannot be found.

**Comment by rndkeith** [comment]
This has been resolved with the latest pull request.
